// Codes d'erreur exacts du cahier des charges (spec §8).
export type ErrorCode =
  | 'AUTH_INVALID_PIN'
  | 'AUTH_TOO_MANY_ATTEMPTS'
  | 'AUTH_SESSION_EXPIRED'
  | 'BUSINESS_READ_ONLY'
  | 'SUBSCRIPTION_EXPIRED'
  | 'QUOTA_PRODUCTS_REACHED'
  | 'QUOTA_USERS_REACHED'
  | 'PRODUCT_NOT_FOUND'
  | 'PRODUCT_HAS_HISTORY'
  | 'CODE_ALREADY_USED'
  | 'CODE_UNREADABLE'
  | 'CUSTOMER_REQUIRED'
  | 'DISCOUNT_ABOVE_LIMIT'
  | 'DISCOUNT_EXCEEDS_SUBTOTAL'
  | 'PAYMENT_EXCEEDS_REMAINING'
  | 'ORDER_NOT_FOUND'
  | 'ORDER_ALREADY_CANCELLED'
  | 'ORDER_IMMUTABLE'
  | 'MOVEMENT_REASON_REQUIRED'
  | 'CASH_REGISTER_CLOSED'
  | 'CASH_REGISTER_ALREADY_OPEN'
  | 'SYNC_DUPLICATE'
  | 'FORBIDDEN_ROLE'
  | 'RESOURCE_NOT_OWNED'
  | 'VALIDATION_ERROR'
  | 'RATE_LIMITED'
  | 'SERVER_ERROR';

const STATUS_BY_CODE: Record<ErrorCode, number> = {
  AUTH_INVALID_PIN: 401,
  AUTH_TOO_MANY_ATTEMPTS: 429,
  AUTH_SESSION_EXPIRED: 401,
  BUSINESS_READ_ONLY: 403,
  SUBSCRIPTION_EXPIRED: 402,
  QUOTA_PRODUCTS_REACHED: 403,
  QUOTA_USERS_REACHED: 403,
  PRODUCT_NOT_FOUND: 404,
  PRODUCT_HAS_HISTORY: 409,
  CODE_ALREADY_USED: 409,
  CODE_UNREADABLE: 422,
  CUSTOMER_REQUIRED: 422,
  DISCOUNT_ABOVE_LIMIT: 403,
  DISCOUNT_EXCEEDS_SUBTOTAL: 422,
  PAYMENT_EXCEEDS_REMAINING: 422,
  ORDER_NOT_FOUND: 404,
  ORDER_ALREADY_CANCELLED: 409,
  ORDER_IMMUTABLE: 409,
  MOVEMENT_REASON_REQUIRED: 422,
  CASH_REGISTER_CLOSED: 409,
  CASH_REGISTER_ALREADY_OPEN: 409,
  SYNC_DUPLICATE: 200,
  FORBIDDEN_ROLE: 403,
  RESOURCE_NOT_OWNED: 404,
  VALIDATION_ERROR: 400,
  RATE_LIMITED: 429,
  SERVER_ERROR: 500,
};

export class AppError extends Error {
  readonly code: ErrorCode;
  readonly details?: unknown;

  constructor(code: ErrorCode, message: string, details?: unknown) {
    super(message);
    this.name = 'AppError';
    this.code = code;
    this.details = details;
  }

  get status(): number {
    return STATUS_BY_CODE[this.code] ?? 500;
  }
}
